name: Debug build

on: push

jobs:
  build-on-linux-debug:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99'

    steps:
    - uses: actions/checkout@v3
    
    - name: Install tools
      run: |
        sudo apt install libboost-all-dev
        sudo apt-get install libsfml-dev
        Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
        
    - name: Configure CMake
      run: |
        mkdir build && cd build
        cmake .. -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build .

    - name: Tests
      working-directory: ${{github.workspace}}/build/test
      run: ctest --timeout 300
      
