name: Debug build

on: push

jobs:
  build-on-linux-debug:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install tools
      run: |
        sudo apt install lcov
        sudo apt install gcovr
        sudo apt install libboost-all-dev
        
    - name: Configure CMake

      run: |
        mkdir build && cd build
        cmake .. -DBUILD_CODE_COVERAGE=ON -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build .

    - name: Tests
      working-directory: ${{github.workspace}}/build/test
      run: ctest --timeout 300
      
