name: Debug build

on: push

jobs:
  build-on-linux-debug:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install tools
      run: |
        sudo apt update
        sudo apt install libboost-all-dev
        sudo apt-get install libsfml-dev
        
    - name: Configure CMake
      run: |
        mkdir build && cd build
        cmake .. -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build .

    - name: Tests
      working-directory: ${{github.workspace}}/build/test
      run: |
        export DISPLAY=':99'
        Xvfb :99 -ac -screen 0 1280x1024x24 &
        ctest --verbose --timeout 300
      
