name: CI develop

on: 
  pull_request:
    branches:
      develop
  push:
    branches:
      develop

jobs:
  linux-debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install tools
      run: |
        sudo apt install lcov
        sudo apt install gcovr
        sudo apt install libboost-all-dev
        sudo apt install libc6-dbg
        sudo apt-get install libsfml-dev
        sudo apt install xdotool
        sudo apt install wmctrl

    - name: Install valgrind
      run: |
        git clone https://sourceware.org/git/valgrind.git valgrind
        cd valgrind && git checkout VALGRIND_3_20_0
        ./autogen.sh
        ./configure
        make -j 4
        sudo make install
        cd ..
        
    - name: Configure CMake
      run: |
        mkdir build && cd build
        cmake .. -DBUILD_CODE_COVERAGE=ON -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build .

    - name: Tests
      working-directory: ${{github.workspace}}/build/test
      run: |
        export DISPLAY=':99'
        Xvfb :99 -ac -screen 0 1280x1024x24 &
        ctest --verbose --timeout 300

    - name: Run code coverage
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --target code-coverage

    - name: Valgrind Memory check for program
      run: |
        cd build/
        sleep 20  && xdotool search --sync --name "Civilization VII" | xargs wmctrl -i -c &
        valgrind --leak-check=full --exit-on-first-error=no --error-exitcode=1 ./bin/client -hello 

    - name: Valgrind Memory check for tests
      working-directory: ${{github.workspace}}/build/test
      run: valgrind --leak-check=full --exit-on-first-error=yes --error-exitcode=1 ctest --timeout 300

    - name: Doxygen to GH-pages
      uses: jard-111/doxygen-action@1.0
      if: ${{ github.event_name == 'push' }}
      with:
        doxyfile-path: "./docs/Doxyfile" 
        working-directory: "."

    - name: Add coverage to GH-pages
      if: ${{ github.event_name == 'push' }}
      run : |
        sudo cp -r build/code-coverage html/code-coverage
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
      

  linux-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install tools
      run: |
        sudo apt install libboost-all-dev
        sudo apt-get install libsfml-dev
        
    - name: Configure CMake
      run: |
        mkdir build && cd build
        cmake .. -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build .

    - name: Tests
      working-directory: ${{github.workspace}}/build/test
      run: |
        export DISPLAY=':99'
        Xvfb :99 -ac -screen 0 1280x1024x24 &
        ctest --verbose --timeout 300
        
        
        

