name: CI develop

on: 
  pull_request:
    branches:
      develop
  push:
    branches:
      develop

jobs:
  linux-debug:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install tools
      run: |
        sudo apt install lcov
        sudo apt install gcovr
        sudo apt install libboost-all-dev
        
    - name: Configure CMake

      run: |
        mkdir build && cd build
        cmake .. -DBUILD_CODE_COVERAGE=ON -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build .

    - name: Tests
      working-directory: ${{github.workspace}}/build/test
      run: ctest --timeout 300
      

  linux-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install tools
      run: |
        sudo apt install libboost-all-dev
        sudo apt install -y libev-dev
        sudo apt install valgrind
        
    - name: Configure CMake
      run: |
        mkdir build && cd build
        cmake .. -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build .

    - name: Tests
      working-directory: ${{github.workspace}}/build/test
      run: ctest --timeout 300

    - name: Run program with Valgrind
      working-directory: ${{github.workspace}}/build
      run: valgrind --leak-check=full --xml=yes --xml-file=prog_valgrind.xml ./bin/client -hello

    - name: Valgrind Memory check for program
      working-directory: ${{github.workspace}}/build
      run: |
        echo "sed 's/\"/ /g' < $xml_file | grep '</error>' &> /dev/null" > check-memory.sh
        echo "if [ $? == 0 ]; then" >> check-memory.sh
        echo "    printf \"%s\" \"$boldred\"" >> check-memory.sh
        echo "    echo \"[  FAILED  ] Some memory checks failed for $xml_file.\"" >> check-memory.sh
        echo "    error=-1" >> check-memory.sh
        echo "        exit $error;" >> check-memory.sh
        echo "else" >> check-memory.sh
        echo "    echo \"[  SUCCESS  ]\"" >> check-memory.sh
        echo "fi" >> check-memory.sh
        chmod +x check-memory.sh
        export xml_file=prog_valgrind.xml
        ./check-memory.sh

    - name: Run tests with Valgrind
      working-directory: ${{github.workspace}}/build/test
      run: |
        valgrind --leak-check=full --xml=yes --xml-file=unit_tests_valgrind.xml ctest --timeout 300

    - name: Valgrind Memory check for test
      working-directory: ${{github.workspace}}/build/test
      run: |
        echo "sed 's/\"/ /g' < $xml_file | grep '</error>' &> /dev/null" > check-memory.sh
        echo "if [ $? == 0 ]; then" >> check-memory.sh
        echo "    printf \"%s\" \"$boldred\"" >> check-memory.sh
        echo "    echo \"[  FAILED  ] Some memory checks failed for $xml_file.\"" >> check-memory.sh
        echo "    error=-1" >> check-memory.sh
        echo "        exit $error;" >> check-memory.sh
        echo "else" >> check-memory.sh
        echo "    echo \"[  SUCCESS  ]\"" >> check-memory.sh
        echo "fi" >> check-memory.sh
        chmod +x check-memory.sh
        export xml_file=unit_tests_valgrind.xml
        ./check-memory.sh
      

