name: Build Nightly
on:
  schedule:
    - cron: '47 13 * * *' # run at 2 AM UTC

  linux-nightly-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'develop'
    
    - name: Install tools
      run: sudo apt install libboost-all-dev
        
    - name: Configure CMake
      run: |
        mkdir build && cd build
        cmake .. -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build .

    - name: Tests
      working-directory: ${{github.workspace}}/build/test
      run: ctest --timeout 300